# Generated by Django 3.2.6 on 2021-09-23 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Rare_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('description', models.CharField(max_length=350)),
                ('image_1', models.ImageField(upload_to='images/post_images')),
                ('image_2', models.ImageField(default=None, null=True, upload_to='images/post_images')),
                ('price', models.PositiveIntegerField()),
                ('availablity_status', models.BooleanField(default=True)),
                ('posted_at', models.DateTimeField()),
                ('category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Rare_app.category')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
