# Generated by Django 3.2.6 on 2021-09-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rare_app', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/post_images'),
        ),
    ]
