# Generated by Django 3.2.6 on 2021-10-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rare_app', '0006_alter_post_image_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/post_images'),
        ),
    ]
