# Generated by Django 3.2.6 on 2021-10-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rare_app', '0008_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='asked_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
