# Generated by Django 3.2.6 on 2021-12-07 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Rare_app', '0009_alter_faq_asked_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.PositiveBigIntegerField()),
                ('adhar', models.ImageField(upload_to='images/artist_adhar_images')),
                ('address', models.CharField(max_length=500)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
