# Generated by Django 3.2.6 on 2021-12-07 10:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Rare_app', '0010_artist_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artist_details',
            new_name='Artist_detail',
        ),
    ]
