# Generated by Django 3.2.6 on 2021-12-10 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Rare_app', '0012_artist_detail_active_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist_detail',
            name='artist',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
