# Generated by Django 3.2.6 on 2021-12-10 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Rare_app', '0013_alter_artist_detail_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist_detail',
            name='active_status',
        ),
    ]
