# Generated by Django 3.2.6 on 2022-01-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rare_app', '0019_auto_20220107_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='cart_products', to='Rare_app.Post'),
        ),
    ]
