# Generated by Django 3.2.6 on 2022-01-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rare_app', '0020_alter_cart_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('message', models.TextField(max_length=1000)),
                ('subject', models.TextField(max_length=100)),
                ('email', models.TextField(max_length=50)),
            ],
        ),
    ]
