# Generated by Django 3.2.6 on 2022-01-14 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Rare_app', '0024_alter_customercontact_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercontact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
