# Generated by Django 3.2.6 on 2022-01-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rare_app', '0026_auto_20220115_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercontact',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customercontact',
            name='state',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customercontact',
            name='totalamt',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='customercontact',
            name='zip',
            field=models.PositiveIntegerField(),
        ),
    ]
