# Generated by Django 3.2.6 on 2022-01-15 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Rare_app', '0027_auto_20220115_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='holder',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart_holder', to=settings.AUTH_USER_MODEL),
        ),
    ]
