# Generated by Django 3.2.6 on 2023-03-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rare_app', '0030_auto_20230322_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customercontact',
            name='totalamt',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='cart',
        ),
        migrations.AddField(
            model_name='orders',
            name='ordered_products',
            field=models.ManyToManyField(related_name='ordered_products', to='Rare_app.Post'),
        ),
    ]
