# Generated by Django 3.2.6 on 2023-03-24 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rare_app', '0032_auto_20230323_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Rare_app.customercontact'),
        ),
    ]
